[general]

framerate = 60
bars = 32

autosens = 1
sensitivity = 100

scaling = logarithmic

method = pipewire
source = auto

sample_rate = 48000
sample_bits = 16
channels = 2


[output]

method = raw
channels = mono

raw_target = /dev/stdout

data_format = ascii
ascii_max_range = 1000

bar_delimiter = 59
frame_delimiter = 10
